Homework html
Yuliia-1988/QA-Manual pull request #1
Opened 2023-12-04 22:34 UTC by Yuliia-1988

2023-12-06 15:37 UTC, Settt requested changes

2023-12-06 15:37 UTC, Settt commented on Homework-HTML/index.html
> +  <link rel="icon" type="image/x-icon" href="C:/Users/User/QA/QA-Manual/Homework-HTML/img/images.png">
Потрібно треба давати не повний шлях до файлу, а так званий відносний. 
Так як ти його дала зараз - в мене на компʼютері не відображається цей файл. Бо в мене немає ні диску C, ні папки User і так далі. 
Тобі потрібно вказати шлях відносно `index.html`. Тобто просто `img/images.png`

2023-12-06 15:37 UTC, Settt commented on Homework-HTML/index.html
> +        <li> <a href="contact.html">
То ж відностний шлях треба зробити і для цього посилання. В тебе contact.html знаходиться в папці pages. Отже треба вказати href="pages/contact.html"

2023-12-06 15:37 UTC, Settt commented on Homework-HTML/index.html
> +        <li><a href="gallery.html">Gallery</a></li>
те саме й тут

2023-12-06 15:37 UTC, Settt commented on Homework-HTML/index.html
> +      <img src="C:/Users/User/QA/QA-Manual/Homework-HTML/img/photo_2023-12-03_16-17-24.jpg" alt="photo_2023-12-03_16-17-24.jpg" class="center" style="width:40%;">
поправ посилання. і alt - текст все ж краще писати як опис до фотографії. Навряд чи людина з обмеженням по зору здогадається що таке `photo_2023-12-03_16-17-24` коли йому це озвучить screen-reader :)

2023-12-06 15:37 UTC, Settt commented on Homework-HTML/index.html
> +        <div> <img src="C:/Users/User/QA/QA-Manual/Homework-HTML/img/photo_2023-12-03_16-16-36.jpg" alt="photo_2023-12-03_16-16-36.jpg" style="width:100%;"></div>
посилання і альт

2023-12-06 15:37 UTC, Settt commented on Homework-HTML/pages/contact.html
> +        <li><a href="index.html">Homepage</a></li>
А тут треба вийти з папки pages.  `../index.htm`

2023-12-06 15:37 UTC, Settt commented on Homework-HTML/pages/gallery.html
> +    <li><a href="index.html">Homepage</a></li>
посилання

2023-12-06 15:37 UTC, Settt commented on Homework-HTML/pages/gallery.html
> +  <a target="_blank" href="C:/Users/User/HTML/img/photo_2023-12-03_16-17-07.jpg">
посилання поправити. Тут і всюди нижче

2023-12-06 15:37 UTC, Settt commented on Homework-HTML/pages/gallery.html
> +    <img src="photo_2023-12-03_16-17-07.jpg" alt="Utthita Hasta Padangusthasana 2">
посилання поправити. А тут вже альт вірний!

2023-12-07 07:44 UTC, Settt requested changes

2023-12-07 07:44 UTC, Settt commented on Homework-HTML/pages/gallery.html
> +    <img src="photo_2023-12-03_16-17-07.jpg" alt="Utthita Hasta Padangusthasana 2">
Тут як раз посилання і залишилося не вірним. Для <img> src має бути ../img/.....

2023-12-07 07:46 UTC, Settt commented on Homework-HTML/index.html
> +  <link rel="icon" type="image/x-icon" href="C:/Users/User/QA/QA-Manual/Homework-HTML/img/images.png">
👌

2023-12-07 07:46 UTC, Settt commented on Homework-HTML/index.html
> +        <li> <a href="contact.html">
👌

2023-12-07 14:31 UTC, Yuliia-1988 commented
Check please, I've already fixed this :)

2023-12-08 09:00 UTC, Settt approved these changes
Looks good!

2023-12-08 12:38 UTC, merged